name: Build and Deploy Retention App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Package build output
        run: tar -czf retention-app.tar.gz ./build  # Zmienna 'build' to folder, który chcesz spakować

      - name: Upload to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./retention-app.tar.gz  # Plik, który chcesz wysłać
          remote-dir: /path/to/remote/directory  # Ścieżka na serwerze FTP
